import { ArmResource, Entity as ADKEntity } from "@zorse/adk";

export class grafana extends ArmResource<grafanaComponentInputs> implements grafanaComponentOutputs {
	constructor(entity: ADKEntity, options: grafanaComponentInputs) {
		super(entity, options.name, "Microsoft.Dashboard/grafana", "2022-08-01", options);
	}
	public readonly apiVersion: "2022-08-01";
	public readonly id: string;
	public readonly type: "Microsoft.Dashboard/grafana";
}
export interface grafanaComponentOutputs {
	readonly apiVersion: "2022-08-01";
	readonly id: string;
	readonly type: "Microsoft.Dashboard/grafana";
}
export interface grafanaComponentInputs {
	readonly identity?: ManagedServiceIdentity | undefined;
	readonly location?: string | undefined;
	readonly name: string;
	readonly properties?: ManagedGrafanaProperties | undefined;
	readonly sku?: ResourceSku | undefined;
	readonly systemData?: SystemData | undefined;
	readonly tags?: ManagedGrafanaTags | undefined;
}
export class grafana_privateEndpointConnections
	extends ArmResource<grafana_privateEndpointConnectionsComponentInputs>
	implements grafana_privateEndpointConnectionsComponentOutputs
{
	constructor(entity: ADKEntity, options: grafana_privateEndpointConnectionsComponentInputs) {
		super(entity, options.name, "Microsoft.Dashboard/grafana/privateEndpointConnections", "2022-08-01", options);
	}
	public readonly apiVersion: "2022-08-01";
	public readonly id: string;
	public readonly type: "Microsoft.Dashboard/grafana/privateEndpointConnections";
}
export interface grafana_privateEndpointConnectionsComponentOutputs {
	readonly apiVersion: "2022-08-01";
	readonly id: string;
	readonly type: "Microsoft.Dashboard/grafana/privateEndpointConnections";
}
export interface grafana_privateEndpointConnectionsComponentInputs {
	readonly name: string;
	readonly properties?: PrivateEndpointConnectionProperties | undefined;
	readonly systemData?: SystemData | undefined;
}
export class grafana_privateLinkResources
	extends ArmResource<grafana_privateLinkResourcesComponentInputs>
	implements grafana_privateLinkResourcesComponentOutputs
{
	constructor(entity: ADKEntity, options: grafana_privateLinkResourcesComponentInputs) {
		super(entity, options.name, "Microsoft.Dashboard/grafana/privateLinkResources", "2022-08-01", options);
	}
	public readonly apiVersion: "2022-08-01";
	public readonly id: string;
	public readonly type: "Microsoft.Dashboard/grafana/privateLinkResources";
}
export interface grafana_privateLinkResourcesComponentOutputs {
	readonly apiVersion: "2022-08-01";
	readonly id: string;
	readonly type: "Microsoft.Dashboard/grafana/privateLinkResources";
}
export interface grafana_privateLinkResourcesComponentInputs {
	readonly name: string;
	readonly properties?: PrivateLinkResourceProperties | undefined;
	readonly systemData?: SystemData | undefined;
}
export interface AzureMonitorWorkspaceIntegration {
	readonly azureMonitorWorkspaceResourceId?: string | undefined;
}
export interface GrafanaIntegrations {
	readonly azureMonitorWorkspaceIntegrations?: AzureMonitorWorkspaceIntegration[] | undefined;
}
export interface ManagedGrafanaProperties {
	readonly apiKey?: ("Disabled" | "Enabled") | undefined;
	readonly autoGeneratedDomainNameLabelScope?: "TenantReuse" | undefined;
	readonly deterministicOutboundIP?: ("Disabled" | "Enabled") | undefined;
	readonly endpoint?: string | undefined;
	readonly grafanaIntegrations?: GrafanaIntegrations | undefined;
	readonly grafanaVersion?: string | undefined;
	readonly outboundIPs?: string[] | undefined;
	readonly privateEndpointConnections?: PrivateEndpointConnection[] | undefined;
	readonly provisioningState?:
		| (
				| "Accepted"
				| "Canceled"
				| "Creating"
				| "Deleted"
				| "Deleting"
				| "Failed"
				| "NotSpecified"
				| "Succeeded"
				| "Updating"
		  )
		| undefined;
	readonly publicNetworkAccess?: ("Disabled" | "Enabled") | undefined;
	readonly zoneRedundancy?: ("Disabled" | "Enabled") | undefined;
}
export interface ManagedGrafanaTags {
	readonly "[ key: string ]"?: string | undefined;
}
export interface ManagedServiceIdentity {
	readonly principalId?: string | undefined;
	readonly tenantId?: string | undefined;
	readonly type: "None" | "SystemAssigned" | "SystemAssigned,UserAssigned" | "UserAssigned";
	readonly userAssignedIdentities?: UserAssignedIdentities | undefined;
}
export interface PrivateEndpoint {
	readonly id?: string | undefined;
}
export interface PrivateEndpointConnection {
	readonly id?: string | undefined;
	readonly name?: string | undefined;
	readonly properties?: PrivateEndpointConnectionProperties | undefined;
	readonly systemData?: SystemData | undefined;
	readonly type?: string | undefined;
}
export interface PrivateEndpointConnectionProperties {
	readonly groupIds?: string[] | undefined;
	readonly privateEndpoint?: PrivateEndpoint | undefined;
	readonly privateLinkServiceConnectionState: PrivateLinkServiceConnectionState;
	readonly provisioningState?: ("Creating" | "Deleting" | "Failed" | "Succeeded") | undefined;
}
export interface PrivateLinkResourceProperties {
	readonly groupId?: string | undefined;
	readonly provisioningState?:
		| (
				| "Accepted"
				| "Canceled"
				| "Creating"
				| "Deleted"
				| "Deleting"
				| "Failed"
				| "NotSpecified"
				| "Succeeded"
				| "Updating"
		  )
		| undefined;
	readonly requiredMembers?: string[] | undefined;
	readonly requiredZoneNames?: string[] | undefined;
}
export interface PrivateLinkServiceConnectionState {
	readonly actionsRequired?: string | undefined;
	readonly description?: string | undefined;
	readonly status?: ("Approved" | "Pending" | "Rejected") | undefined;
}
export interface ResourceSku {
	readonly name: string;
}
export interface SystemData {
	readonly createdAt?: string | undefined;
	readonly createdBy?: string | undefined;
	readonly createdByType?: ("Application" | "Key" | "ManagedIdentity" | "User") | undefined;
	readonly lastModifiedAt?: string | undefined;
	readonly lastModifiedBy?: string | undefined;
	readonly lastModifiedByType?: ("Application" | "Key" | "ManagedIdentity" | "User") | undefined;
}
export interface UserAssignedIdentities {
	readonly "[ key: string ]"?: UserAssignedIdentity | undefined;
}
export interface UserAssignedIdentity {
	readonly clientId?: string | undefined;
	readonly principalId?: string | undefined;
}
export default {
	grafana: grafana,
	"grafana/privateEndpointConnections": grafana_privateEndpointConnections,
	"grafana/privateLinkResources": grafana_privateLinkResources,
};
